apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.appName }}
#  namespace: namespace-calculator
  labels:
    app: {{  .Values.appLabel }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{  .Values.appLabel }}
  template:
    metadata:
      labels:
        app:  {{  .Values.appLabel }}
    spec:
      containers:
      - name: c-calculator
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
